-- Andre Ceschia: 501156295
-- Numair Jaan: 501113345
-- Ty Tsiamala: 501168084

SELECT * FROM USERS;

SELECT * FROM BENIFICARY;

SELECT * FROM REWARDS_ACCOUNT;

SELECT * FROM CONTACT_INFO;

SELECT * FROM ACCOUNT;

SELECT * FROM CHEQUING_ACCOUNT;

SELECT * FROM SAVINGS_ACCOUNT;

SELECT * FROM transactions;